/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Couleurs par défaut (conservées)
        surface: "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3fd",
        "surface-container": "#ededf8",
        "surface-container-high": "#e7e7f2",
        "surface-container-highest": "#e1e2ec",
        "surface-variant": "#e1e2ec",
        "on-surface": "#191b23",
        "on-surface-variant": "#434654",
        primary: "#003d9b",
        "primary-container": "#0052cc",
        "on-primary": "#ffffff",
        "on-primary-container": "#c4d2ff",
        secondary: "#4f5f7b",
        "secondary-container": "#cdddff",
        "on-secondary-container": "#51617e",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#8c0000",
        outline: "#737685",
        "outline-variant": "#c3c6d6",
        // Couleurs Monster Hunter Wilds
        "on-tertiary": "#343029",
        "tertiary-fixed-dim": "#cec5bb",
        "primary-fixed": "#ffddb5",
        "secondary-fixed": "#ede1ce",
        background: "#151310",
        "tertiary-container": "#9f978e",
        "surface-tint": "#f6bc6f",
        "on-primary-fixed": "#2a1800",
        "inverse-on-surface": "#33302d",
        "on-tertiary-fixed-variant": "#4b463e",
        "on-tertiary-container": "#343029",
        "on-secondary": "#363023",
        "on-secondary-fixed-variant": "#4d4638",
        "on-secondary-fixed": "#201b0f",
        "on-primary-fixed-variant": "#643f00",
        "primary-fixed-dim": "#f6bc6f",
        "inverse-surface": "#e8e1dc",
        "tertiary-fixed": "#eae1d7",
        "on-tertiary-fixed": "#1f1b15",
        "on-surface-variant": "#d4c4b3",
        "on-primary-container": "#452a00",
        "surface-container-low": "#1d1b18",
        "surface-container-highest": "#373431",
        "surface-container": "#211f1c",
        "tertiary": "#cec5bb",
        "on-background": "#e8e1dc",
        "inverse-primary": "#815511",
        "surface-bright": "#3b3935",
        "surface-dim": "#151310",
        "secondary-fixed-dim": "#d0c5b3",
        "outline-variant": "#504538",
        "surface-container-high": "#2c2a26",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};




